name: hash
description: A set of cryptographic hashing functions implemented in pure Dart
version: 2.0.0
homepage: https://github.com/olgeer/hash

environment:
  sdk: '>=2.12.0 <3.0.0'


dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
